"""
ghidra_decompiler.code_utils
-----------------------------
Utilities for inspecting and sanitizing decompiled C code strings.

Public API
----------
    sanitize_c_code(c_code)     -> str
    is_generic_name(name)       -> bool
    clean_c_argument(arg_str)   -> str
"""

import re
from ghidra_decompiler.syntax import recover_variadic_arguments


def sanitize_c_code(c_code):
    """
    Performs multiple sanitization passes on the C code:
    1. Converts hexadecimal numbers (0x...) to decimal.
    2. Converts boolean literals (true, false) to integers (1, 0).
    3. Simplifies subtraction-based comparisons (x - 1U == 0 -> x == 1).
    4. Recovers missing variadic arguments (e.g. scanf).

    Skips over string literals to avoid corrupting text.
    """
    if not c_code:
        return c_code

    # Split the C code by C-style string literals (handling escaped quotes).
    # Parts at even indices are code, odd indices are strings.
    parts = re.split(r'("(?:\\.|[^"\\])*")', c_code)

    for i in range(0, len(parts), 2):
        # Pass 1: Convert hex to decimal.
        parts[i] = re.sub(
            r'\b0[xX][0-9a-fA-F]+\b',
            lambda match: str(int(match.group(0), 16)),
            parts[i]
        )

        # Pass 2: Convert boolean literals to integers.
        parts[i] = re.sub(r'\btrue\b',  '1', parts[i])
        parts[i] = re.sub(r'\bfalse\b', '0', parts[i])

        # Pass 3: Simplify subtraction-based comparisons (e.g., x - 1U == 0 -> x == 1)
        parts[i] = re.sub(
            r'\b([a-zA-Z_][a-zA-Z0-9_]*)\s*-\s*(\d+)U?\s*([=!]=)\s*0\b',
            r'\1 \3 \2',
            parts[i]
        )

    final_c = "".join(parts)
    
    # Pass 4: Clean up remaining (ulong)(var - constU) artifacts
    # This converts (ulong)(selected_option - 6U) -> (selected_option - 6)
    final_c = re.sub(
        r'\(ulong\)\s*\(\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*-\s*(\d+)U?\s*\)',
        r'(\1 - \2)',
        final_c
    )
    
    # Pass 5: Strip 'U' suffix from any remaining integers for readability
    final_c = re.sub(r'\b(\d+)U\b', r'\1', final_c)

    # Pass 6: Strip unused variadic arguments from printf
    # If printf has a constant string with no % and more than 1 argument, strip the others.
    final_c = re.sub(
        r'(printf\s*\(\s*"([^%"]*)"\s*)\s*,[^;]*\)',
        r'\1)',
        final_c
    )

    # Pass 7: Recover missing variadic arguments (e.g. scanf)
    final_c = recover_variadic_arguments(final_c)
    
    return final_c


def is_generic_name(name):
    """Check if a name matches Ghidra's autogenerated naming scheme."""
    generic_pattern = (
        r'^(param_\d+|local_[0-9a-fA-F]+|uVar\d+|iVar\d+|'
        r'sVar\d+|cVar\d+|undefined.*)$'
    )
    return bool(re.match(generic_pattern, name))


def clean_c_argument(arg_str):
    """Strip modifiers like &, *, and casts from C argument strings."""
    arg_str = re.sub(r'^[&\*]+', '', arg_str)
    arg_str = re.sub(r'^\([^)]+\)\s*', '', arg_str)
    return re.sub(r'^[&\*]+', '', arg_str).strip()
