"""
ghidra_decompiler.code_utils
-----------------------------
Utilities for inspecting and sanitizing decompiled C code strings.

Public API
----------
    sanitize_c_code(c_code)     -> str
    is_generic_name(name)       -> bool
    clean_c_argument(arg_str)   -> str
"""

import re


def sanitize_c_code(c_code):
    """
    Performs multiple sanitization passes on the C code:
    1. Converts hexadecimal numbers (0x...) to decimal.
    2. Converts boolean literals (true, false) to integers (1, 0).

    Skips over string literals to avoid corrupting text.
    """
    if not c_code:
        return c_code

    # Split the C code by C-style string literals (handling escaped quotes).
    # Parts at even indices are code, odd indices are strings.
    parts = re.split(r'("(?:\\.|[^"\\])*")', c_code)

    for i in range(0, len(parts), 2):
        # Pass 1: Convert hex (like 0x1A or 0x0) to decimal.
        parts[i] = re.sub(
            r'\b0[xX][0-9a-fA-F]+\b',
            lambda match: str(int(match.group(0), 16)),
            parts[i]
        )

        # Pass 2: Convert boolean literals to integers.
        parts[i] = re.sub(r'\btrue\b',  '1', parts[i])
        parts[i] = re.sub(r'\bfalse\b', '0', parts[i])

    return "".join(parts)


def is_generic_name(name):
    """Check if a name matches Ghidra's autogenerated naming scheme."""
    generic_pattern = (
        r'^(param_\d+|local_[0-9a-fA-F]+|uVar\d+|iVar\d+|'
        r'sVar\d+|cVar\d+|undefined.*)$'
    )
    return bool(re.match(generic_pattern, name))


def clean_c_argument(arg_str):
    """Strip modifiers like &, *, and casts from C argument strings."""
    arg_str = re.sub(r'^[&\*]+', '', arg_str)
    arg_str = re.sub(r'^\([^)]+\)\s*', '', arg_str)
    return re.sub(r'^[&\*]+', '', arg_str).strip()
