"""
ghidra_decompiler.gui_utils.optimizer
-------------------------------------
Applies programmatic P-Code level variable splits to eliminate intermediate dead
captures (like transient iVar1 assigned from printf) directly from the live
Ghidra GUI Decompiler view.
"""

def optimize_gui_function_variables(program, func, monitor=None):
    """
    Analyzes the High-Function representation of the target function and renames any
    residual autogenerated temporary variables (e.g. iVar1, uVar3) to clean sequential
    _tmp_N identifiers directly in the live Ghidra program database. This ensures the
    built-in GUI Decompiler view displays intentional, readable pseudocode consistent
    with our static decompiler output pipeline.

    Parameters
    ----------
    program : ghidra.program.model.listing.Program
    func    : ghidra.program.model.listing.Function
    monitor : ghidra.util.task.TaskMonitor, optional
    """
    import re
    from ghidra.app.decompiler import DecompInterface
    from ghidra.util.task import ConsoleTaskMonitor
    from ghidra.program.model.pcode import HighFunctionDBUtil
    from ghidra.program.model.symbol import SourceType

    if monitor is None:
        monitor = ConsoleTaskMonitor()

    # Decompile the function in GUI context to acquire live local symbols
    iface = DecompInterface()
    iface.openProgram(program)
    try:
        res = iface.decompileFunction(func, 30, monitor)
        if not res.decompileCompleted():
            return

        high_func = res.getHighFunction()
        if not high_func:
            return

        # Iterate over all high-level symbols mapped to local storage
        local_symbols = high_func.getLocalSymbolMap().getSymbols()
        ghidra_tmp_pattern = re.compile(r'^([iusbcf]Var\d+)$')
        
        rename_count = 0
        for sym in local_symbols:
            c_name = sym.getName()
            if c_name and ghidra_tmp_pattern.match(c_name):
                rename_count += 1
                new_name = f"_tmp_{rename_count}"
                try:
                    # Update database storage explicitly so the GUI caches the new name
                    HighFunctionDBUtil.updateDBVariable(sym, new_name, None, SourceType.USER_DEFINED)
                except BaseException:
                    pass

        if rename_count > 0:
            print(f"[GUI Optimizer] Renamed {rename_count} residual temporary variable(s) to _tmp_N in '{func.getName()}'.")

    finally:
        iface.dispose()
